### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by bernard0047** [nianticlabs/airplanes#4]
Thanks for the amazing work!

I have a couple of questions about training:

1. Approximately how long does it take to train the 2D network on the ScanNetV2 dataset to achieve the results reported in the paper, using an A100 GPU?
2. Would it be feasible to train the network on other datasets without modifying the core implementation? Aside from data preparation, what other changes, if any, might be needed?

Thanks!

**Comment by mdfirman** [comment]
Hello, and thanks for your interest!

I don't know exactly how long it might take to train on a single GPU. I don't remember it taking longer than a day or so, but according to our configs I think we trained on 2 GPUs for 110000 steps; if you can figure out how long a single step takes on an A100 you can multiply up from there.

I don't see any reason why you couldn't train on other datasets. However, they would need to have appropriate labels. Note also that our method relies on being able to reconstruct good geometry, so if the depth estimation network can't predict good enough depths then you won't be able to make a good enough mesh of the scene and then the RANSAC step will probably fail.
